// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: 'about', uri: Uri.parse('about'), routeBuilder: b0Builder),
  RouteEntity(
    key: 'lib/app',
    uri: Uri.parse('lib/app'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: 'bike/create',
    uri: Uri.parse('bike/create'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'bike/read/[id]',
    uri: Uri.parse('bike/read/[id]'),
    routeBuilder: b3Builder,
  ),
  RouteEntity(
    key: 'bike/update/[id]',
    uri: Uri.parse('bike/update/[id]'),
    routeBuilder: b4Builder,
  ),
  RouteEntity(
    key: 'contact',
    uri: Uri.parse('contact'),
    routeBuilder: b5Builder,
  ),
  RouteEntity(
    key: 'notfound',
    uri: Uri.parse('notfound'),
    routeBuilder: b6Builder,
  ),
];

const routePaths = (
  path: '/',
  about: '/about',
  lib: (path: '/lib', app: '/lib/app'),
  bike: (
    path: '/bike',
    create: '/bike/create',
    read: (path: '/bike/read', $id: '/bike/read/[id]'),
    update: (path: '/bike/update', $id: '/bike/update/[id]'),
  ),
  contact: '/contact',
  notfound: '/notfound',
);
