// GENERATED FILE. PLEASE DO NOT EDIT THIS FILE!!

part of 'main.dart';

List<RouteEntity> get routes => [
  RouteEntity(key: 'about', uri: Uri.parse('about'), routeBuilder: b0Builder),
  RouteEntity(
    key: 'lib/app',
    uri: Uri.parse('lib/app'),
    routeBuilder: b1Builder,
  ),
  RouteEntity(
    key: 'bike/create',
    uri: Uri.parse('bike/create'),
    routeBuilder: b2Builder,
  ),
  RouteEntity(
    key: 'contact',
    uri: Uri.parse('contact'),
    routeBuilder: b6Builder,
  ),
  RouteEntity(
    key: 'notfound',
    uri: Uri.parse('notfound'),
    routeBuilder: b7Builder,
  ),
];

const routePaths = (
  path: '/',
  about: '/about',
  lib: (path: '/lib', app: '/lib/app'),
  bike: (path: '/bike', create: '/bike/create'),
  contact: '/contact',
  notfound: '/notfound',
);
